In [2]:
5. Write your first code in Python - explore NumPy, Pandas and Matplotlib. Try the
following exercises: simple calculations, print function, script file, Python Notebook,
Python data structure (lists, tuples, dictionaries, JSON data format)
6. Basic programming techniques: branching and looping, vector and matrices, user-
defined functions
7. Object-oriented programming with Python

SyntaxError: invalid syntax (<ipython-input-2-acf20849c50a>, line 2)

In [15]:
# Numpy tutorial

import numpy as np

# Using Numpy to create a array 

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[1])

# creating a zero's array
print(np.zeros(2))

# creating one's array
print(np.ones(2))

# creating an empty array with 2 elements 
print(np.empty(2))

# creating an array with a range of elements 
print(np.arange(4))

# creating an array with given step size
print(np.arange(2, 10, 2))

[1 2 3 4 5 6]
[5 6 7 8]
[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3]
[2 4 6 8]
