In [21]:
# Numpy tutorial

import numpy as np

# Using Numpy to create a array 

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[1])

# creating a zero's array
print(np.zeros(2))

# creating one's array
print(np.ones(2))

# creating an empty array with 2 elements 
print(np.empty(2))

# creating an array with a range of elements 
print(np.arange(4))

# creating an array with given step size
print(np.arange(2, 10, 2))

# use linspace() to create array with values that are spaced linearly in a specified interval
print(np.linspace(0, 10, num = 5))

# specifying data type
x = np.ones(2, dtype = np.int64)
print(x)

# adding, removing and sorting elements 
arr = np.array([2, 1, 5, 4, 15, 7, 3])
print(np.sort(arr))
print(np.argsort(arr))
print(np.searchsorted(arr, 19))

# concatenate()
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(np.concatenate((arr1, arr2)))

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(np.concatenate((x, y), axis = 0))

# to know the shape and size of an array 

arr3 = np.array([[[0, 1, 2, 3],
                  [4, 5, 6, 7]], 
                  
                  [[0, 1, 2, 3,], 
                   [4, 5, 6, 7]],
                  
                  [[0, 1, 2, 3],
                   [4, 5, 6, 7]]])

print(arr3)
print(arr3.ndim)
print(arr3.size)
print(arr3.shape)


[1 2 3 4 5 6]
[5 6 7 8]
[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[1 1]
[ 1  2  3  4  5  7 15]
[1 0 6 3 2 5 4]
7
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]
[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
3
